version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username1
      - MONGO_INITDB_ROOT_PASSWORD=password1
      - MONGO_INITDB_DATABASE=database1
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    command: ['redis-server', '/usr/local/etc/redis/redis.conf', '--appendonly', 'yes']
    ports:
      - 6379:6379

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/database1

      
    

