services:
  frontend-test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - BACKEND_URL=http://backend:3000
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    