GET http://localhost:3000/api/persons/

###
DELETE http://localhost:3000/api/persons/4

###
PUT http://phonebook-a3ue.onrender.com/api/persons/
content-type: application/json

{
  "name": "w",
  "number": "123"
}

###
POST http://localhost:3000/api/persons/
content-type: application/json

{
  "name": "s",
  "number": "123"
}